---
- name: conf app server
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: all
  roles:
     - consul

- name: ssh add known_hosts
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - ssh

- name: conf app server
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: all
  roles:
     - generic

- name: conf galera
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: db
  roles:
     - mariadb

- name: conf nginx server
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: balancer
  roles:
     - nginx


- name: conf app server
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: app
  roles: 
     - tomcat
     - java
     - oms


- name: conf app server
  gather_facts: True
  become: yes
  become_method: sudo
  hosts: Galera2
  roles: 
     - restoredb


