---
- name: restart master
  shell: service mysql restart --wsrep-new-cluster
  listen: restart master node

- name: restart mariadb
  service: name=mariadb state=restarted
  listen: restart mariadb

- name: start mariadb
  service: name=mariadb state=started
  listen: start mariadb