---
- name: ssh
  command: /usr/bin/ssh-keyscan -T 10 {{ ansible_host }}
  register: keyscan
- lineinfile: name=~/.ssh/known_hosts create=yes line={{ item }}
  with_items: '{{ keyscan.stdout_lines }}'